#!/bin/bash

# Check if a full path to the project directory was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <full-path-to-project-directory>"
    exit 1
fi

PROJECT_PATH=$1

# Create the project directory if it doesn't exist
mkdir -p $PROJECT_PATH

# Create the .vscode directory structure
mkdir -p $PROJECT_PATH/.vscode

# Create the .vscode/launch.json file
cat <<EOL > $PROJECT_PATH/.vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Main",
            "request": "launch",
            "mainClass": "Main",
            "classPaths": [
                "\${workspaceFolder}/bin"
            ],
            "console": "integratedTerminal"
        }
    ]
}
EOL

# Create the .vscode/tasks.json file
cat <<EOL > $PROJECT_PATH/.vscode/tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "javac",
            "args": [
                "-d",
                "bin",
                "*.java"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "\$javac"
            ],
            "detail": "Generated by Java Extension Pack"
        }
    ]
}
EOL

# Create a sample Main.java file in the root directory
cat <<EOL > $PROJECT_PATH/Main.java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
EOL

# Create a README.md file in the root directory
cat <<EOL > $PROJECT_PATH/README.md
# Java Project Template

This is a template for Java projects in Visual Studio Code.

## Setup

- Place your Java files in the project root directory.
- Use the build task (\`Cmd+Shift+B\` or \`Ctrl+Shift+B\`) to compile.
- Use the launch configuration (\`F5\`) to run your application.
EOL

echo "Java project '$PROJECT_PATH' created successfully."
